services:
  db:
    image: postgres:15-alphine
    container_name: fustan_db
    restart: always
    environment:
      POSTGRES_USER: fustan_user
      POSTGRES_PASSWORD: fustan_password
      POSTGRES_DB: fustan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fustan_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fustan.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
